base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path('route', views.route, name="route"),
    path('map', views.map, name="map"),
]

gapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('base.urls', namespace="base")),
    path('', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = "users"
urlpatterns = [
	
	path('', views.AccountView.as_view(), name="account"),
	path('profile', views.profile_view, name="profile"),
	path('sign-up', views.SignUpView.as_view(), name="sign-up"),
	path('sign-in', views.SignInView.as_view(), name="sign-in"),
	path('sign-out', views.sign_out, name="sign-out"),
	]

templates/partials/logo.html
{% load static %}
<a href="{% url 'users:account' %}">
	<div class="brand-logo">
		<img class="logo" src="{% static 'branding/did_logo.gif' %}" />
	</div>
</a>

templates/partials/nav.html
{% if request.user.is_authenticated %}
<ul class="sidenav">
  {% if request.path == "/" %}
  <li><a class="active" href="{% url 'users:account' %}">User Account</a></li>
  {% else %}
  <li><a href="{% url 'users:account' %}">User Account</a></li>
  {% endif %}

  {% if "profile" in request.path %}
  <li><a class="active" href="{% url 'users:profile' %}">User Profile</a></li>
  {% else %}
  <li><a href="{% url 'users:profile' %}">User Profile</a></li>
  {% endif %}

  {% if "route" in request.path %}
  <li><a class="active" href="{% url 'main:route' %}">Route</a></li>
  {% else %}
  <li><a href="{% url 'main:route' %}">Route</a></li>
  {% endif %}

  {% if "map" in request.path %}
  <li><a class="active" href="{% url 'main:map' %}">Map</a></li>
  {% else %}
  <li><a href="{% url 'main:map' %}">Map</a></li>
  {% endif %}

  {% if "sign-out" in request.path %}
  <li><a class="active" href="{% url 'users:sign-out' %}">Sign Out</a></li>
  {% else %}
  <li><a href="{% url 'users:sign-out' %}">Sign Out</a></li>
  {% endif %}
  
</ul>
{% else %}
<ul class="sidenav">

  {% if "sign-in" in request.path %}
  <li><a class="active" href="{% url 'users:sign-in' %}">Sign In</a></li>
  {% else %}
  <li><a href="{% url 'users:sign-in' %}">Sign In</a></li>
  {% endif %}
  
  {% if "sign-up" in request.path %}
  <li><a class="active" href="{% url 'users:sign-up' %}">Sign Up</a></li>
  {% else %}
  <li><a href="{% url 'users:sign-up' %}">Sign Up</a></li>
  {% endif %}
</ul>
{% endif %}